---

- name: NTP Test2
  hosts: mci-rtr01
  gather_facts: false

  tasks:
    - name: Configure NTP Servers
      cisco.ios.ios_ntp_global:
        config:
          servers:
            - server: 10.10.10.10
            - server: 14.14.14.14
            - server: 16.16.16.16
        state: replaced