---

- name: NTP Test
  hosts: mci-rtr01
  gather_facts: false

  tasks:
    - name: Configure NTP Servers
      cisco.ios.ios_config:
        lines:
          - ntp server 13.13.13.13
          - ntp server 10.10.10.10
          - ntp server 12.12.12.12
        match: exact
        replace: line
        diff_against: running

